Resources:
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
        - AttributeName: EventName
          AttributeType: S
        - AttributeName: EventDate
          AttributeType: S
        - AttributeName: EventStatus
          AttributeType: S
        - AttributeName: EventCity
          AttributeType: S
        - AttributeName: NumberEntries
          AttributeType: N
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH

      # >>> Activar PITR (restauraciones hasta 35 días atrás)
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      # (Opcional) Evita borrado accidental de la tabla:
      # DeletionProtectionEnabled: true

      GlobalSecondaryIndexes:
        - IndexName: EventNameIndex
          KeySchema:
            - AttributeName: EventName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventDateIndex
          KeySchema:
            - AttributeName: EventDate
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventStatusIndex
          KeySchema:
            - AttributeName: EventStatus
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: EventCityIndex
          KeySchema:
            - AttributeName: EventCity
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: NumberEntriesIndex
          KeySchema:
            - AttributeName: NumberEntries
              KeyType: HASH
          Projection:
            ProjectionType: ALL
