AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creaci칩n de EventBridge Scheduler para activar una Lambda que cambiar치 el estado del evento.

Resources:

  ## Rol que EventBridge usar치 para invocar la Lambda ##
  EventBridgeInvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EventBridgeSchedulerInvokeLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17" 
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt LambdaB.Arn

  ## EventBridge Scheduler para ejecuci칩n puntual ##
  MyScheduledEvent:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: MyScheduledLambdaExecution
      ScheduleExpression: 'at(2025-10-10T15:00:00Z)'  # Fecha y hora UTC
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt LambdaB.Arn
        RoleArn: !GetAtt EventBridgeInvokeLambdaRole.Arn
        Input: !Sub |
          {
            "id": "test-123",
            "fecha": "2025-10-10T15:00:00Z"
          }
