AWSTemplateFormatVersion: '2010-09-09'
Description: >
  EventBridge Scheduler que invoca la Lambda de actualización a una hora programada.

Parameters:
  UpdateLambdaFunctionArn:
    Type: String
    Description: ARN de la Lambda destino (UpdateEventLambda) que será invocada por el Scheduler.

  ScheduleExpression:
    Type: String
    Default: ""
    Description: Expresión de schedule (ej. cron(0 12 * * ? *)); si se deja vacío, no se crea el schedule.

  InputPayload:
    Type: String
    Default: "{}"
    Description: JSON que se enviará como input a la Lambda.

Conditions:
  HasScheduleExpression: !Not [!Equals [!Ref ScheduleExpression, ""]] 

Resources:
  EventBridgeInvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "EBSchedInvoke-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com 
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AllowInvokeTargetLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref UpdateLambdaFunctionArn

  UpdateLambdaSchedule:
    Type: AWS::Scheduler::Schedule
    Condition: HasScheduleExpression
    Properties:
      Name: !Sub "update-lambda-schedule-${AWS::StackName}"
      FlexibleTimeWindow:
        Mode: OFF
      ScheduleExpression: !Ref ScheduleExpression
      Target:
        Arn: !Ref UpdateLambdaFunctionArn
        RoleArn: !GetAtt EventBridgeInvokeLambdaRole.Arn
        Input: !Ref InputPayload
      State: ENABLED

Outputs:
  ScheduleName:
    Condition: HasScheduleExpression
    Description: Nombre del schedule creado
    Value: !Ref UpdateLambdaSchedule

  SchedulerRoleArn:
    Description: ARN del role usado por EventBridge Scheduler
    Value: !GetAtt EventBridgeInvokeLambdaRole.Arn
