AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack para desplegar S3 -> DynamoDB -> Lambdas -> API Gateway como nested stacks.

Parameters:
  TemplatesBaseUrl:
    Type: String
    Description: > 
      URL base (sin el archivo) donde están las plantillas hijas en S3.
      Ej: https://s3.amazonaws.com/mi-bucket/cfn (sin la / final)
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qc, pdn]
    Description: Ambiente para los recursos (usado por lambdas.yml).
  Region:
    Type: String
    Default: us-east-1
    Description: Región AWS (pasado a s3.yml).
  EventTableName:
    Type: String
    Default: EventTable
    Description: Nombre de la tabla DynamoDB (consumido por lambdas.yml).
  ApiKeyName:
    Type: String
    Default: events-api-key
    Description: Nombre del API Key en API Gateway.
  ApiKeyValue:
    Type: String
    Default: ""
    NoEcho: true
    Description: >
      (Opcional) Valor del API Key. Si va vacío, api-gateway.yml debe soportar crear el key y exponer el Id para consultarlo luego.

Resources:

  #S3Stack:
  #  Type: AWS::CloudFormation::Stack
  #  Properties:
  #    TemplateURL: !Sub "${TemplatesBaseUrl}/s3.yml"
  #    Parameters:
  #      Enviroment: !Ref Environment  # Nota: param escrito así en tu template s3.yml
  #      Region: !Ref Region

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/dynamodb.yml"

  LambdasStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DynamoDBStack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/lambdas.yml"
      Parameters:
        Environment: !Ref Environment
        EventTableName: !Ref EventTableName

  ApiGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdasStack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/api-gateway.yml"
      Parameters:
        LambdaFunctionArn: !GetAtt [LambdasStack, Outputs.LambdaArn]
        ApiKeyName: !Ref ApiKeyName

  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LambdasStack
    Properties:
      TemplateURL: !Sub "${TemplatesBaseUrl}/eventbridge.yml"
      Parameters:
        UpdateLambdaFunctionArn: !GetAtt [LambdasStack, Outputs.UpdateLambdaArn]